[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -Isrc
    -Isrc/web
    -Isrc/core
    -Isrc/system
    -Isrc/utils
lib_deps =
    majicdesigns/MD_MAX72XX@^3.5.1

[env:native]
platform = native
build_flags = -std=c++11 -DBUILD_FOR_TESTS=1
test_build_src = false
