[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Дополнительные параметры и флаги компиляции можно добавить здесь
; Например:
; upload_port = /dev/tty.SLAB_USBtoUART
; build_flags = -DDEBUG
